spring.application.name=Springbootregistationpage
spring.application.name=Springbootregistationpage
spring.datasource.url=jdbc:mysql://localhost:3306/thyme
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=vaibhav
spring.jpa.hibernate.ddl-auto=update
